---

   - name: Include plugin vars
     include_vars: "../defaults/{{ EDSI_TEMPLATE_NAME }}.yml"

   - name: VDB Source config
     set_fact: 
        DELPHIX_VDB_SOURCECONFIG_PARAMETERS: 1
     when: DELPHIX_VDB_TEMP_SC|length!=0 

   - name: create dxtoolkit configuration
     template: src=dxtools.conf.j2 dest="{{ DXLOC }}/dxtools.conf" mode=755

   - name: create dsource ingestion script
     template: src=adddsource.j2 dest="{{ playbook_dir }}/adddsource.sh" mode=755
     when: dxtoolkit == False

   - name: create vdb provision  script
     template: src=addvdb.j2 dest="{{ playbook_dir }}/addvdb.sh" mode=755
     when: dxtoolkit == False
